mud-to-clay:
  nether-delay-seconds: 2
  magma-delay-seconds: 15
trampling:
  steps-per-stage: 20
crops:
  wither-chance: 0.3
  splash-radius: 6
biomes:
  thresholds:
    hot-min-temp: 1.5
    dry-max-hum: 0.2
    cold-max-temp: 0.3
    wet-min-hum: 0.7
  modifiers:
    crop-wither:
      hot: 1.5
      wet: 0.3
      cold: 0.7
      temperate: 1.0
    trample:
      hot: 0.7
      wet: 1.5
      cold: 1.2
      temperate: 1.0
backpack-upgrades:
  tick-interval: 5
  magnet-radius:
    magnet: 4
    advanced-magnet: 8
